### ISSUE TITLE
Java Code Upgrade

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/csi-sira#724]
Check and eventually upgrade java code projects too (all the folders with java code inside the frontend folder, and the backend folder).

The CSI-SIRA project has also a backend part developed in JAVA. We have to ensure that backend part is still working with the backend dependencies used by the last version of MS and the required Java version (minimum v8).

@dsuren1 is involved here to verify and test/check if the csi-sira backend is still working properly after the update
@taba90 will be involved only if something in that backend need to be updated/fixed according to the above.

**Comment by taba90** [comment]
An issue that needs to be fixed regards spring dependencies:

- GeoServer updated to 2.17.x has spring dependecies of version 5.1.13 and spring security 5.1.8

- other csi-sira modules have spring and spring security dependecies of version 3.0.5 that needs to be updated

-  in order to make build and tests to be successfull it is necessary to updates dependecies on the entire project, frontend module included, to avoid conflicting versions.

- but geostore is using spring/spring security version 3.x

Given this we need to update geostore spring dependency either on master or in a custom branch.
Otherwise when deploying the entire application exception will be thrown due conflicting spring versions
