### ISSUE TITLE
Map multi selection from filter

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/csi-sira#763]
It is required to develop a feature that allows to select multiple objects of multiple layers in the map starting from a WFS record.

### Requirement
Select in the map the N features belonging to layers connected to the selected WFS record whose geometry represents the bounding containing them (this geometry will only have a synthetic value, see example image below). 

![image_2020_10_05T14_19_00_858Z](https://user-images.githubusercontent.com/1280027/95091292-8f581c00-0726-11eb-9d6d-828a3a57753f.png)

**Possible use case**
In order to be geometrically described, a single WFS record of **Progetti di Valutazione** needs a selection of N geometries of N different known layers (Point, Line and Polygon).
The use case starts from a WFS record with an **unique code attribute value** that can be selected (e.g. absolute code of the project). The selected attribute value will be used to select one or more geometries belonging to other connected layers (ie. with the same attribute value). The selected features of other layers will be then highlighted in the map using a blue style.

Detailed requirements: https://drive.google.com/file/d/1VGYdPNaE6uQ_gDozjdBnimKMsOXzs2TR/view?usp=sharing

**Comment by mbarto** [comment]
Configuration:
 - [ ] a specific section in feature types configuration files will be used to contain all the configuration properties for the multilayersection (MLS) functionality
   * [ ] list of layers to be selected / filtered on the map (with filter to be applied for each one, and style for selected items)
   * [ ] attribute path of the main featuretype to be used for selection / filtering

UI:
 - [ ] add a new button to start multilayer selection from a search list (featuregrid) for feature types configured with the new MLS section
 - [ ] add a new button to start multilayer selection from a detail card for feature types configured with the new MLS section

Workflow:
 - [ ] when clicking on any of the new MLS buttons (from list or detail pages) new WMS layers will be added to the map, one for each sublayer configured in the MLS section for the featuretype, with proper filter applied
 - [ ] selected / filtered WMS layers will have a different style from the same base layer in TOC, so that selected items are highlighted

**Comment by mbarto** [comment]
Sample featureType to be used:
 * https://github.com/geosolutions-it/csi-sira/blob/master/frontend/assets/viaFaseProcedimentale.json
 * [ ] we need to add configurations for GeoServer (attached)
 * [ ] we need to check if we have the tables used by the (new) layers in the database

[workspaces.tar.gz](https://github.com/geosolutions-it/csi-sira/files/5375914/workspaces.tar.gz)
[data.tar.gz](https://github.com/geosolutions-it/csi-sira/files/5375915/data.tar.gz)

**Comment by mbarto** [comment]
@dsuren1 now everything should be configured on the GeoServer side, and the database data should be there.
Let me know if this is enough for you to proceed.

**Comment by mbarto** [comment]
These are the connected layers to be shown / filtered on the map:
 * decsiraogc_sivia_geo:decsira_geo_sivia_linea
 * decsiraogc_sivia_geo:decsira_geo_sivia_poligono
 * decsiraogc_sivia_geo:decsira_geo_sivia_punto

**Comment by dsuren1** [comment]
@mbarto 
Under [viaFaseProcedimentale](https://github.com/geosolutions-it/csi-sira/blob/master/frontend/assets/viaFaseProcedimentale.json), the query field typeName  **_decsiraogc_decodif:decsira_d_sivia_fase_categoria_** getAttributeValue calls fails with exception (_exceptionCode="InvalidParameterValue" locator="typeName"_) 
https://decsira-dev.geo-solutions.it/geoserver/ows?service=WFS&request=GetFeature&authkey=&version=1.1.0&outputFormat=application/json&typeName=decsiraogc_decodif:decsira_d_sivia_fase_categoria&propertyName=id_cat,cat_new,descrizione,id_cat_skvia,ordinamento,tipo_categoria&sortBy=ordinamento+A 
Kindly let me know if this is due to the missing feature in geoserver

**Comment by mbarto** [comment]
@dsuren1 yes, this one is missing from GeoServer I am working with @taba90 to restore this and the other namespaces that you already notified me

**Comment by mbarto** [comment]
@dsuren1 should be working now. Let me know if you miss anything else

**Comment by mbarto** [comment]
@dsuren1 a couple of things to fix/check:

 * There is no zoom button on the viaFaseProcedimentale search list, is there any reason for this? Something missing in configuration? Having the ability to zoom would help identifying the selected geometries
 * lines and points have a wrong style applied (they are both styled as polygons)

**Comment by dsuren1** [comment]
Hi @mbarto 
> @dsuren1 a couple of things to fix/check:
> 
> * There is no zoom button on the viaFaseProcedimentale search list, is there any reason for this? Something missing in configuration? Having the ability to zoom would help identifying the selected geometries

Reason - Data fetched doesn't have coordinates in geometry 

> * lines and points have a wrong style applied (they are both styled as polygons)

I will check this out

**Comment by mbarto** [comment]
> Hi @mbarto
> 
> > @dsuren1 a couple of things to fix/check:
> > 
> > * There is no zoom button on the viaFaseProcedimentale search list, is there any reason for this? Something missing in configuration? Having the ability to zoom would help identifying the selected geometries
> 
> Reason - Data fetched doesn't have coordinates in geometry
> 
@dsuren1 
This is strange, I can see a geometry in WFS responses:

```xml
<decsiraogc_sivia:geometria>
                <gml:Polygon srsDimension="2" srsName="http://www.opengis.net/gml/srs/epsg.xml#4326">
                    <gml:exterior>
                        <gml:LinearRing>
                            <gml:posList>7.85049846 44.42158703 7.85046529 44.42327922 7.85522554 44.42332703 7.85525857 44.42163484 7.85049846 44.42158703</gml:posList>
                        </gml:LinearRing>
                    </gml:exterior>
                </gml:Polygon>
            </decsiraogc_sivia:geometria>
```

Maybe it's a matter of correcly configuring the geometry to use in JSON?

**Comment by dsuren1** [comment]
Yes @mbarto . The xpath is incorrect for geometry. I have given a fix in this [PR ](https://github.com/geosolutions-it/csi-sira/pull/801)

**Comment by mbarto** [comment]
@dsuren1 we have some feedbacks from the client, asking for some changes:
 * the zoom to (both from the list item and when you click on multi selection) is not showing the whole geometries (both the main one and the selected ones); I believe it's because of the fixed zoom we set when zooming, and I also believe we should do a real zoom to extent there (let's see what is wrong with the current extent to zoom calculation)
 * when clicking on multi layer selection we currently create 3 layers (point, lines, polygons) and add them to the TOC, this has to change in the following way:
  - we want to add the layers configured in multi selection without a filter, with their original style (no custom SLD)
  - the selection is an additional layer, with custom SLD styles and proper filters; if possible we should have only one layer for the whole selection in TOC (not 3 as in the current example)
  - the color for the selected geometries should not be the usual blue, but #00FFFF

Let's talk if you have doubts or need to clarify anything.

**Comment by dsuren1** [comment]
Sure @mbarto

**Comment by dsuren1** [comment]
> * the zoom to (both from the list item and when you click on multi selection) is not showing the whole geometries (both the main one and the selected ones); I believe it's because of the fixed zoom we set when zooming, and I also believe we should do a real zoom to extent there (let's see what is wrong with the current extent to zoom calculation)

Currently the zoom to extent is calculated based on the selected geometry coordinates of the main feature and displays the mls present in this extent

> * when clicking on multi layer selection we currently create 3 layers (point, lines, polygons) and add them to the TOC, this has to change in the following way:
>   
>   * we want to add the layers configured in multi selection without a filter, with their original style (no custom SLD)

Upon clicking on the MLS icon, all configured layers will be added to TOC with no filter and SLD (from example, this means 3 layers + 1 main layer)
>   * the selection is an additional layer, with custom SLD styles and proper filters; if possible we should have only one layer for the whole selection in TOC (not 3 as in the current example)

Following an additional selected layer will be added with filter and SLD and this will be in hidden group?

@mbarto Kindly advise

**Comment by mbarto** [comment]
For example, with a linear geometry, I have this: (searching for Anno 2003 - Provincia TORINO, item with "Codice Procedimento" = "2003/149 - VER-TO")

![image](https://user-images.githubusercontent.com/2770528/98556836-c67c9880-22a3-11eb-9e26-02dfaa54d1d9.png)

I would expect something like this:

![image](https://user-images.githubusercontent.com/2770528/98557041-fd52ae80-22a3-11eb-9633-b4b38920ef7b.png)

**Comment by mbarto** [comment]
> Upon clicking on the MLS icon, all configured layers will be added to TOC with no filter and SLD (from example, this means 3 layers + 1 main layer)

Correct.

> Following an additional selected layer will be added with filter and SLD and this will be in hidden group?
Yes, remember this layer should contain the selection for all the sublayers (in the example 3). I don't know if this is simple enough,. let me know.


> I also stumbled upon an existing issue, where, the style type of vector layer added on selection of a row from main feature is always 'point' and this leads to layer not getting highlighted, when the main feature is of type 'Polygon'

Oh, now I understand why selection of an item was not showing.

**Comment by mbarto** [comment]
@dsuren1 I summarize the remaining things to do here with a couple more things to look at:
 - [ ] fix zoom to behaviour to show the main feature and connected features bounding box fully
 - [ ] add connected layers, unfiltered and with original style to the TOC on selection
 - [ ] add selection to the map (for all connected layers) as one single (hidden in TOC) layer, removed when the catalog is closed
 - [ ] change selected geometries color to #00FFFF (preserving the old color for normal selection from the list)

These are the additional things to check / improve:

 - [ ] update documentation with new configuration items (I can take care of this)
 - [ ] add an additional connected layer (from an external WMS) to the example we are working on. These are the details:
     * source WMS: http://geomap.reteunitaria.piemonte.it/ws/gsareprot/rp-01/areeprotwms/wms_gsareprot_1?service=WMS&version=1.1.1&request=getCapabilities (this is not GeoServer, so it probably does not support the cql_filter param, and we will need to user filter instead; we should have in MapStore functions to convert the cql_filter to an XML filter and use that, maybe a flag in layer configuration is needed to decide if we can use cql_filter or not)
     * Layer Title:  'ZSC/SIC - Zone Speciali di Conservazione / Siti di Importanza Comunitaria'
     * feature filter attribute: 'codice_amministrativo' (es. 'IT1201000')
     * main feature attribute for filter 'decsiraogc_sivia:codiceSito' (I think the current single attribute for the main feature cannot cover this use case, we will need to replicate it on all the connected layers, so that we can use a different one for each)
  - [ ] check if you can replicate this error (it looks like the application is trying to load /assets/decsiraogc_sivia_geo:decsira_geo_sivia_punto.json, but I don't know why it happens):

```
"404(Not Found): <!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> The requested resource [/decsiraweb2/assets/decsiraogc_sivia_geo:decsira_geo_sivia_punto.json] is not available</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/7.0.104</h3></body></html>"
```

**Comment by dsuren1** [comment]
Additionally
- [x] Disable MLS icon when main feature has no geometry
- [x] Select features will highlight vector layer based on the geometry type unlike always as 'Point'

**Comment by mbarto** [comment]
@bruncili we implemented the requested changes, except that we could not test the functionality with the sample MapServer WMS given, because it is compatible with some mandatory requirements, in particular WMS filtering, the client is aware of this.
The client can proceed with testing for the final approve
