### ISSUE TITLE
Links in Detail pages crash the application when clicked

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/csi-sira#774]
If you click on the link shown in the image, the app crashes.

![image](https://user-images.githubusercontent.com/2770528/95863271-49bdd380-0d64-11eb-8091-f8170546f162.png)

Connected to #720

**Comment by dsuren1** [comment]
@mbarto 
I found the features which can be queried has missing namespaces, due to which when clicked on the Link scheda, the application crashes. 

Below are the few examples
Example:

1. **_IMPIANTI RECUPERO E SMALTIMENTO RIFIUTI AIA O EX ART. 208_**

xpath getValue 
**Element**: - "/wfs:FeatureCollection/wfs:member/decsiraogc_rifiuti_smaltimento:ImpiantoRifiutiSmaltimAIA208/decsiraogc_rifiuti_smaltimento:stabilimentoSemplice/decsiraogc_rifiuti_smaltimento:StabilimentoSemplice/decsiraogc_rifiuti_smaltimento:codiceSIRA/text()"

**Namespace missing:** decsiraogc_rifiuti_smaltimento  (fails)

**Namespace available**:
decsiraogc_rifiuti_generici: "http://www.regione.piemonte.it/ambiente/decsiraogc_rifiuti_generici/1.0"
gml: "http://www.opengis.net/gml/3.2"
wfs: "http://www.opengis.net/wfs/2.0"
xlink: "http://www.w3.org/1999/xlink"
xs: "http://www.w3.org/2001/XMLSchema"
xsi: "http://www.w3.org/2001/XMLSchema-instance"


2. **_IMPIANTI RECUPERO RIFIUTI AUA O PROCEDURA SEMPLIFICATA (FUORI AUA)_**

xpath getValue 
**Element**: /wfs:FeatureCollection/
wfs:member/
decsiraogc_rifiuti_aua:ImpiantoRifiutiAUAnoAUA/
decsiraogc_rifiuti_aua:stabilimentoSemplice/
decsiraogc_rifiuti_aua:StabilimentoSemplice/
decsiraogc_rifiuti_aua:codiceSira/text()

**Namespace missing**: decsiraogc_rifiuti_aua (fails)

**Namespace available**:
decsiraogc_rifiuti_generici: "http://www.regione.piemonte.it/ambiente/decsiraogc_rifiuti_generici/1.0"
gml: "http://www.opengis.net/gml/3.2"
wfs: "http://www.opengis.net/wfs/2.0"
xlink: "http://www.w3.org/1999/xlink"
xs: "http://www.w3.org/2001/XMLSchema"
xsi: "http://www.w3.org/2001/XMLSchema-instance"

**Comment by mbarto** [comment]
@dsuren1 I had a quick look, and to me the issue seems to be a wong configuration is used for the new detail.
When you click on the link a new featureType should be loaded and configured (impiantoRifiutiGenerico.json), and a new detail template also (cardTemplateImpiantoRifiutiGenerico.jsxt).
The namespaces that are missing are used by the parent featureType (impiantoRifiutiSmaltimAIA208.json), so I think something goes wrong during the switch from the main featureType to the one of the link

**Comment by dsuren1** [comment]
@mbarto 
I checked the code as advised just to be sure if we have introduced something that makes something wrong during the switch and couldn't fine one.
I tried the same with **PROD** version (configuration), the _impiantoRifiutiGenerico.json,_ _cardTemplateImpiantoRifiutiGenerico.jsxt_ are identical to dev version. The only difference I could find is the response of the service call where it fetches the typename **decsiraogc_rifiuti_generici:ImpiantoRifiutiGenerico**
URL: 
[DEV Link](https://decsira-dev.geo-solutions.it/geoserver/ows?service=WFS&request=GetFeature&typeName=decsiraogc_rifiuti_generici:ImpiantoRifiutiGenerico&version=2.0&srsName=EPSG:4326&cql_filter=decsiraogc_rifiuti_generici:identificativoRifiutoGenerico=%27800066_101_102%27)

[PROD Link](http://conoscenzaambientale.sistemapiemonte.it/decsiraweb/proxy/?url=http%3A%2F%2Fgisserver.territorio.csi.it%2Fgeoserver%2Fows%3Fservice%3DWFS%26request%3DGetFeature%26typeName%3Ddecsiraogc_rifiuti_generici%3AImpiantoRifiutiGenerico%26version%3D2.0%26srsName%3DEPSG%3A4326%26cql_filter%3Ddecsiraogc_rifiuti_generici%3AidentificativoRifiutoGenerico%3D%27800066_101_102%27)

**Dev** version, the **_namespaces_** brought in the responses are
xmlns:wfs="http://www.opengis.net/wfs/2.0"	
xmlns:xs="http://www.w3.org/2001/XMLSchema"	
xmlns:decsiraogc_rifiuti_generici="http://www.regione.piemonte.it/ambiente/decsiraogc_rifiuti_generici/1.0"	xmlns:gml="http://www.opengis.net/gml/3.2"	
xmlns:xlink="http://www.w3.org/1999/xlink"	
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

**PROD** version, the _**namespace**_ brought in response are
xmlns:wfs="http://www.opengis.net/wfs/2.0"
xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:it.geosolutions="http://www.geo-solutions.it"
xmlns:decsiraogc_rifiuti_aua="http://www.regione.piemonte.it/ambiente/decsiraogc_rifiuti_aua/1.0"
xmlns:decsiraogc_rifiuti_generici="http://www.regione.piemonte.it/ambiente/decsiraogc_rifiuti_generici/1.0"
xmlns:tiger="http://www.census.gov"
xmlns:decsiraogc_emissioni="http://www.regione.piemonte.it/ambiente/decsiraogc_emissioni/1.0"
xmlns:topp="http://www.openplans.org/topp"
xmlns:decsiraogc_rifiuti_smaltimento="http://www.regione.piemonte.it/ambiente/decsiraogc_rifiuti_smaltimento/1.0"
xmlns:decsiraogc_monitor_datidimens="http://www.regione.piemonte.it/ambiente/decsiraogc_monitor_datidimens/1.0"
xmlns:decsiraogc_stabilimenti="http://www.regione.piemonte.it/ambiente/decsiraogc_stabilimenti/1.0"
xmlns:decsiraogc_controlli_scarichi_urbani="http://www.regione.piemonte.it/ambiente/decsiraogc_controlli_scarichi_urbani/1.0"
xmlns:sf="http://www.openplans.org/spearfish"
xmlns:decsiraogc_rifiuti_discarica="http://www.regione.piemonte.it/ambiente/decsiraogc_rifiuti_discarica/1.0"
xmlns:decsiraogc_areeprotezione_pta="http://www.regione.piemonte.it/ambiente/decsiraogc_areeprotezione_pta"
xmlns:decsiraogc_monitor_depuratori="http://www.regione.piemonte.it/ambiente/decsiraogc_monitor_depuratori/1.0"
xmlns:cite="http://www.opengeospatial.net/cite"
xmlns:decsiraogc_waste_en="http://www.regione.piemonte.it/ambiente/decsiraogc_waste_en/1.0"
xmlns:decsiraogc_decodif="gisserver.territorio.csi.it/decsiraogc_decodif"
xmlns:sde="http://geoserver.sf.net"
xmlns:decsiraogc_siticontaminati="http://www.regione.piemonte.it/ambiente/decsiraogc_siticontaminati/1.0"
xmlns:gml="http://www.opengis.net/gml/3.2"
xmlns:nurc="http://www.nurc.nato.int"
xmlns:decsiraogc_scarichi="http://www.regione.piemonte.it/ambiente/decsiraogc_scarichi/1.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

which seems to be the reason why it works fine when I used the prod configuration locally. Kindly let me know your thoughts

**Comment by mbarto** [comment]
@dsuren1 first thing to notice: the DEV answer is more correct than the production one, because the production one includes all namespaces configured in GeoServer, also if they are not related to the feature we are querying.

This suggests to me that this stuff is working on production due to a bug in GeoServer we don't have anymore.

I presume there is a moment when you are switching between the main feature impiantoRifiutiSmaltimAIA208 and the link feature impiantoRifiutiGenerico where the main feature configuration is used on the link feature data.

I think we have 2 options:
 * understand how to avoid this moment where configuration and data are not aligned (preferred solution)
 * make the "crashing" code not crash if a namespace is missing, returning empty data instead
