### ISSUE TITLE
Complex features count implementation in GeoServer

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/csi-sira#828]
Il decsira per ottenere il numero dei record che si avranno in risposta ad una query utilizza una query simile a questa:

<wfs:GetPropertyValue service="WFS" valueReference='decsiraogc_idf_pfa:provincia'
version="2.0" xmlns:fes="http://www.opengis.net/fes/2.0"
xmlns:gml="http://www.opengis.net/gml/3.2"
xmlns:wfs="http://www.opengis.net/wfs/2.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd">
<wfs:Query typeNames="decsiraogc_idf_pfa:PianiForestaliAziendali"/>
</wfs:GetPropertyValue>

Questa soluzione è inefficiente al punto che in alcuni casi va in time out questa "count" mentre si ottiene la risposta alla query vera e propria.
Essendo passati un po' di anni dalla prima versione del decsira vorremmo sapere se con le attuali tecnologie possiamo ottenere una count su complex feature più efficiente.

**Comment by nmco** [comment]
Writing here the same feedback I wrote on the mail for reference:

> Dear all, Mauro,
> this is not implemented at the moment, but we estimated something similar for a client a few months ago here.
> 
> The computation of the matched features is not implemented for complex features, in practice it will require an extra SQL query to be sent to the database with a count(*). It's also worth noting that in most of the cases that value is not used by the client requesting the system, it's typically used for pagination, this extra SQL query with the count(*) will introduce a performance penalty proportional to the matching cardinality and complexity of the provided WFS filter. Our suggested fix here is to implement the features count, but make it configurable per a layer basis, so it will only be activated for the layers where it's needed and doesn't introduces an excessive performance penalty, there will also be an option to activate it when pagination is used (limit parameter is provided), our estimate is 16 hours.
> 
> Let me know if you need more details.
> 
> Kind regards,
> Nuno Oliveira

**Comment by simboss** [comment]
@nmco the client has given us green light.

When do you think we can deliver?

**Comment by nmco** [comment]
@simboss we will deliver this by the end of next week, @taba90 has an urgent task for Vianova.

**Comment by taba90** [comment]
working on this

**Comment by simboss** [comment]
cool, keep us posted.

**Comment by taba90** [comment]
@nmco 

- a count for app-schema exists even if it is not invoked in the FeatureCollection size() method.
- the existing count, counts root feature only thus it works for Query all and for Filter with a not nested attribute.
- the count when nested attributtes are involved can be implemented using the [FeatureChainedAttributeVisitor](https://github.com/geotools/geotools/blob/master/modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/FeatureChainedAttributeVisitor.java) to visit the filter getting the chaining information and build the [QueryJoins ](https://github.com/geotools/geotools/blob/1b4c81fc632b4c0a106593a957925f57861e5a9d/modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/joining/JoiningQuery.java#L34) to be passed to the JDBCJoiningFeatureSource which seems able to handle[ as many joins are needed ](https://github.com/geotools/geotools/blob/cb942b512235187bc37d13cf09b29163a235fd5a/modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java#L398). The count will then be computed iterating the FeatureIterator.
- I would then make configurable only the count when filtering on nested attributes since the already implemented count is efficient as long as counts root features only.

**Comment by nmco** [comment]
Meeting minutes of 25-01-2021:
- There two count values returned, numberMatched and numberReturned.
- NumberReturned it's computed using XSLT and doesn't add too much computation overhead.
- numberMatched it's more tricky, since it requires a count query to be send to the DB.
- By default numberReturned shoudl be activated and numberMatched deactivated (-1 should be returned), It should be possible to activate or deactivate them separatly in the UI per workspace or layer.

**Comment by simboss** [comment]
I need to give them an ETA.
Help! @taba90 @nmco

**Comment by nmco** [comment]
@simboss, quick awnser the ETA is Friday.

The PR will be submitted for review tomorrow the latest, @taba90 a few reminders:
- We will need to update App-Schema integration tests (both off-line, PostgresSQL and Oracle ones), @fernandor777 can help running these.
- The documentation will need to be updated.
- Since this is a fix, it can be and should be back-ported to 2.19.x and 2.18.x.

@mbarto let's know if the client needs backport to a specific branch or custom build.

**Comment by mbarto** [comment]
@nmco they have a custom build depending on 2.17-SNAPSHOT as you can see here: https://github.com/geosolutions-it/csi-sira/blob/master/geoserver/src/pom.xml#L1687

So they will need a backport to the 2.17.x branch

**Comment by taba90** [comment]
pull requests  have been made details in jira tickets 
https://osgeo-org.atlassian.net/browse/GEOT-6794
https://osgeo-org.atlassian.net/browse/GEOS-9879

**Comment by simboss** [comment]
@mbarto can you review these PRs?

**Comment by mbarto** [comment]
@simboss I surely can. I believe also @nmco should (if he didn't already), since he is more expert than me on the topic

**Comment by simboss** [comment]
@taba90 there is feedback and questions both on GT as well as on GS for you to address.

**Comment by nmco** [comment]
@simboss yes we will handle those, thx for the heads up, we actually had to fix a problem whit a test, today after lunch things will be answered and merged.

**Comment by taba90** [comment]
pr merged on master backports are pending. details here ([gt jira ticket](https://osgeo-org.atlassian.net/browse/GEOT-6794) and [gs jira ticket](https://osgeo-org.atlassian.net/browse/GEOS-9879))

**Comment by taba90** [comment]
backports merged

**Comment by mbarto** [comment]
@taba90 I did a quick test on our dev server (https://decsira-dev.geo-solutions.it/geoserver/ows?service=WFS), with the following WFS query:

```xml
<wfs:GetFeature startIndex="0" count="20" service="WFS" version="2.0" xmlns:wfs="http://www.opengis.net/wfs/2.0" xmlns:fes="http://www.opengis.net/fes/2.0" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd">
    <wfs:Query typeNames="decsiraogc_sivia:FaseProcedura" srsName="EPSG:4326">
        <fes:Filter>
            <fes:And>
                <fes:PropertyIsEqualTo>
                    <fes:ValueReference>decsiraogc_sivia:localizzazione/decsiraogc_sivia:Localizzazione/decsiraogc_sivia:desProvincia</fes:ValueReference>
                    <fes:Literal>ALESSANDRIA</fes:Literal>
                </fes:PropertyIsEqualTo>
            </fes:And>
        </fes:Filter>
    </wfs:Query>
</wfs:GetFeature>
```

As you can see the query filter is on a nested property.

This is a fragment of the response I get:

```xml
<wfs:FeatureCollection ... numberMatched="unknown" numberReturned="20" ...>
    <wfs:member>
        <decsiraogc_sivia:FaseProcedura gml:id="100610">
           ...
        </decsiraogc_sivia:FaseProcedura>
    </wfs:member>
    ...
</wfs:FeatureCollection>
```

As you can see the numberMatched attribute is still unknown. Do we need to do any configuration step to enable the patch to work in our environment?

**Comment by nmco** [comment]
Talk whit @taba90 16-02-2021:
- This is a consequence of a problem when re-factoring the PR.
- A test was only added for the result hits but not for the normal get feature, hence this was not detected.
- @taba90 will fix this as top priority.
- Take over: Test things properly.
- The count is also now activated by default since we are using the already existing option to activate or deactivate it, which means that certain users may see a performance penalty when upgrading GeoServer, I don't like this but there is not straightforward solution to handle this properly.

Thank you for your detailed report @mbarto !

**Comment by taba90** [comment]
@mbarto now everything should be fine on the server.

**Comment by mbarto** [comment]
@taba90 yes, I can confirm, thanks
