### ISSUE TITLE
Dev server GeoserverUI redirect to not existing url when performing common operations 

### ISSUE THREAD

**Issue by taba90** [geosolutions-it/csi-sira#843]
When performing common operation on the Geoserver  UI deployed in dev server, like saving a layer or change page number, geoserver redirect to not existing url. 
This does not happen when accessing it through IP [http://92.222.205.35:8080/geoserver/web](http://92.222.205.35:8080/geoserver/web).

The problem arised after having redeployed a patched geoserver 2.17.x with the feature count functionality.
@taba90 performed the following operation: backup war and datadir, place the new war in the webapps directory and change user permissions from root to tomcat. Restart tomcat.

**Comment by giacomoc92** [comment]
@mbarto what's the priority with this?

**Comment by randomorder** [comment]
high @giacomoc92

**Comment by giacomoc92** [comment]
This is what happens while creating a new store through the reverse proxy. we get a 400 for this url
![image](https://user-images.githubusercontent.com/49372260/109333489-cf4ba700-785f-11eb-8059-77f8232f5bc1.png)

while bypassing the proxy, we get a 302 to the correct page and can create a new store

![image](https://user-images.githubusercontent.com/49372260/109333965-61ec4600-7860-11eb-9860-cb4c9795dac9.png)

It also works while using http instead of https.
![image](https://user-images.githubusercontent.com/49372260/109334730-66fdc500-7861-11eb-9481-f9a0a906a0db.png)

The issue is probably in how geoserver handles requests from the https virtualhost or the virtualhost itself.

**Comment by randomorder** [comment]
https://docs.geoserver.org/stable/en/user/configuration/globalsettings.html#proxy-base-url ?

**Comment by nmco** [comment]
What's the status on this @taba90 ?

**Comment by randomorder** [comment]
that could be [the CSRF](https://docs.geoserver.org/stable/en/user/security/webadmin/csrf.html#csrf-protection) in GeoServer @giacomoc92

**Comment by giacomoc92** [comment]
should be sorted @taba90 please give it a try
